import React from "react";
import { Composition } from "remotion";
import { MyComposition } from "./Composition";

import { CleanTestScene, EmailFeature, SceneHook, SceneWorkspaceAssembly, Hook, SceneNotionAIMagic, Workspace, SceneOutro, IntroProductReveal, SalesTrendsScene, CustomerLTV, BenefitActionableGrowth, CTAStartGrowing, HappyFarmers, GrowthStruggleHook, SalesTrendsAnalysis, ActionableGrowth, MetricsQuestionHook, SalesOverviewScene, FeatureCustomerInsights, BenefitRevenueGrowth, CallToAction, GrowthInfo, EcommerceChallengeHook, SalesPerformanceTracker, HookComplexityChallenge, IntroTesting212, AutomatedAnalysis, CollaborativeWorkflows, BenefitTimeEfficiency, CTAGetStarted, AutomatedAnalysisScene, HookProductivity, IntroVoiceOSAssistant, FeatureCalendar, EmailReplyFeature, BenefitTimeStress, HookManualCodingPain, EffortlessProductivityHook, IntroVoiceOS, VoiceCommandsScene, SmartMeetingSummaries, BenefitTimeSaving, BouncingBall, HookDigitalChaos, IntroTestOS, MovingLogo, HookOverwhelmedFeeling, HookFutureWork, IntroSynergyOS, TaskManagementFeature, HookManyTabs, IntroProductName, PriceTrackingFeature, FeatureComparison, BenefitSaveScene, CTAStartShopping, HookOTPDelay, IntroApiIntegration, FeatureProcessingDelivery, FeatureVerificationSecurity, CtaBrandLockup } from "./scenes";

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="MyComp"
        component={MyComposition}
        durationInFrames={60}
        fps={30}
        width={1280}
        height={720}
      />
      <Composition
        id="clean-test-scene"
        component={CleanTestScene}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-email"
        component={EmailReplyFeature}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-emai"
        component={EmailFeature}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="scene-hook"
        component={SceneHook}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="scene-workspace-assembly"
        component={SceneWorkspaceAssembly}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook"
        component={Hook}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="scene-notion-ai-magic"
        component={SceneNotionAIMagic}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="workspace"
        component={Workspace}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="scene-outro"
        component={SceneOutro}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook-growth-struggle"
        component={GrowthStruggleHook}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="intro-product-reveal"
        component={IntroProductReveal}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-sales-trends"
        component={SalesTrendsAnalysis}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-customer-ltv"
        component={CustomerLTV}
        durationInFrames={145}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="benefit-actionable-growth"
        component={ActionableGrowth}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="cta-start-growing"
        component={CTAStartGrowing}
        durationInFrames={110}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="happy-farmers-scene"
        component={HappyFarmers}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook-metrics-question"
        component={MetricsQuestionHook}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-sales-overview"
        component={SalesOverviewScene}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-customer-insights"
        component={FeatureCustomerInsights}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="benefit-revenue-growth"
        component={BenefitRevenueGrowth}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="cta-start-free-trial"
        component={CallToAction}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="growth-info-scene"
        component={GrowthInfo}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook-ecommerce-challenge"
        component={EcommerceChallengeHook}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-sales-performance"
        component={SalesPerformanceTracker}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook-complexity-challenge"
        component={HookComplexityChallenge}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="intro-testing-212"
        component={IntroTesting212}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-automated-analysis"
        component={AutomatedAnalysisScene}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-collaborative-workflows"
        component={CollaborativeWorkflows}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="benefit-time-efficiency"
        component={BenefitTimeEfficiency}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook-productivity"
        component={HookProductivity}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="intro-voiceos-assistant"
        component={IntroVoiceOSAssistant}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-calendar"
        component={FeatureCalendar}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="benefit-time-stress"
        component={BenefitTimeStress}
        durationInFrames={130}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook-manual-coding-pain"
        component={HookManualCodingPain}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook-effortless-productivity"
        component={EffortlessProductivityHook}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="intro-voiceos"
        component={IntroVoiceOS}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-voice-commands"
        component={VoiceCommandsScene}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="feature-smart-summaries"
        component={SmartMeetingSummaries}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="benefit-time-saving"
        component={BenefitTimeSaving}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="bouncing-ball-scene"
        component={BouncingBall}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="bouncing-ball-scene-v2"
        component={BouncingBall}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="hook-digital-chaos"
        component={HookDigitalChaos}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="intro-testos"
        component={IntroTestOS}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="moving-logo-scene"
        component={MovingLogo}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
            <Composition
        id="hook-overwhelmed-feeling"
        component={HookOverwhelmedFeeling}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="hook-future-work"
        component={HookFutureWork}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="intro-synergyos"
        component={IntroSynergyOS}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-task-management"
        component={TaskManagementFeature}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="hook-many-tabs"
        component={HookManyTabs}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
                      <Composition
        id="intro-product-name"
        component={IntroProductName}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="hook-many-tabs-v2"
        component={HookManyTabs}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-price-tracking"
        component={PriceTrackingFeature}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="feature-comparison"
        component={FeatureComparison}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="benefit-save"
        component={BenefitSaveScene}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="cta-start-shopping"
        component={CTAStartShopping}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="hook-otp-delay"
        component={HookOTPDelay}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="intro-api-integration"
        component={IntroApiIntegration}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-processing-delivery"
        component={FeatureProcessingDelivery}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-verification-security"
        component={FeatureVerificationSecurity}
        durationInFrames={130}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="cta-brand-lockup"
        component={CtaBrandLockup}
        durationInFrames={100}
        fps={30}
        width={1920}
        height={1080}
      />
    </>
  );
};
