import React from "react";
import { Composition } from "remotion";
import { MyComposition } from "./Composition";

import { EmailFeature, SceneHook, SceneWorkspaceAssembly, Hook, SceneNotionAIMagic, Workspace, SceneOutro, IntroProductReveal, CustomerLTV, BenefitActionableGrowth, CTAStartGrowing, HappyFarmers, GrowthStruggleHook, SalesTrendsAnalysis, ActionableGrowth, MetricsQuestionHook, SalesOverviewScene, FeatureCustomerInsights, BenefitRevenueGrowth, CallToAction, GrowthInfo, EcommerceChallengeHook, SalesPerformanceTracker, HookComplexityChallenge, IntroTesting212, AutomatedAnalysis, CollaborativeWorkflows, BenefitTimeEfficiency, AutomatedAnalysisScene, HookProductivity, IntroVoiceOSAssistant, FeatureCalendar, EmailReplyFeature, BenefitTimeStress, HookManualCodingPain, EffortlessProductivityHook, IntroVoiceOS, VoiceCommandsScene, SmartMeetingSummaries, BenefitTimeSaving, BouncingBall, HookDigitalChaos, IntroTestOS, MovingLogo, HookProblemIntro, APIIntegrationScene, VerificationSecurity, TestScene, FeatureApiIntegration, FeatureProcessingDelivery, BenefitVerificationSecurity, InterswitchBrandOutro, ProblemIntro, APIIntegration, ProcessingDeliveryScene, SceneOutroBrand, CtaGetStarted, ProblemIntroMinimal, ProblemProductIntro, ApiIntegration, ProcessingDelivery, BenefitsOutro, AppleParticleReveal, AppleParticleRevealSmart, LinearMotion, LinearReveal, LinearLogoAnimation, LinearLogo, LinearLogoReveal, AIAutomationScene, FeatureTeamCollaboration, BenefitTimeFocus, MotionArtScene, CleanTestScene, ChatGPTLogoScene, DigitalChaosHook, HookUnseenForce, IntroRedefined, FeatureIntegration, AIPoweredThinkingHook, ChatGPTCTA } from "./scenes";
export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="MyComp"
        component={MyComposition}
        durationInFrames={60}
        fps={30}
        width={1280}
        height={720}
      />
                    <Composition
        id="feature-email"
        component={EmailReplyFeature}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
              <Composition
        id="feature-emai"
        component={EmailFeature}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="scene-hook"
        component={SceneHook}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="scene-workspace-assembly"
        component={SceneWorkspaceAssembly}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="hook"
        component={Hook}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="scene-notion-ai-magic"
        component={SceneNotionAIMagic}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="workspace"
        component={Workspace}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                      <Composition
        id="scene-outro"
        component={SceneOutro}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
                      <Composition
        id="hook-growth-struggle"
        component={GrowthStruggleHook}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
                            <Composition
        id="intro-product-reveal"
        component={IntroProductReveal}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="feature-sales-trends"
        component={SalesTrendsAnalysis}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
                            <Composition
        id="feature-customer-ltv"
        component={CustomerLTV}
        durationInFrames={145}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="benefit-actionable-growth"
        component={ActionableGrowth}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="cta-start-growing"
        component={CTAStartGrowing}
        durationInFrames={110}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="happy-farmers-scene"
        component={HappyFarmers}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="hook-metrics-question"
        component={MetricsQuestionHook}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-sales-overview"
        component={SalesOverviewScene}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-customer-insights"
        component={FeatureCustomerInsights}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="benefit-revenue-growth"
        component={BenefitRevenueGrowth}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="cta-start-free-trial"
        component={CallToAction}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="growth-info-scene"
        component={GrowthInfo}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="hook-ecommerce-challenge"
        component={EcommerceChallengeHook}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-sales-performance"
        component={SalesPerformanceTracker}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
                            <Composition
        id="hook-complexity-challenge"
        component={HookComplexityChallenge}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                      <Composition
        id="intro-testing-212"
        component={IntroTesting212}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="feature-automated-analysis"
        component={AutomatedAnalysisScene}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="feature-collaborative-workflows"
        component={CollaborativeWorkflows}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="benefit-time-efficiency"
        component={BenefitTimeEfficiency}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />

                            <Composition
        id="hook-productivity"
        component={HookProductivity}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="intro-voiceos-assistant"
        component={IntroVoiceOSAssistant}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-calendar"
        component={FeatureCalendar}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="benefit-time-stress"
        component={BenefitTimeStress}
        durationInFrames={130}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="hook-manual-coding-pain"
        component={HookManualCodingPain}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="hook-effortless-productivity"
        component={EffortlessProductivityHook}
        durationInFrames={105}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="intro-voiceos"
        component={IntroVoiceOS}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-voice-commands"
        component={VoiceCommandsScene}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-smart-summaries"
        component={SmartMeetingSummaries}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="benefit-time-saving"
        component={BenefitTimeSaving}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                            <Composition
        id="bouncing-ball-scene"
        component={BouncingBall}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                                  <Composition
        id="hook-digital-chaos"
        component={HookDigitalChaos}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="intro-testos"
        component={IntroTestOS}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="moving-logo-scene"
        component={MovingLogo}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />

          <Composition
        id="bouncing-ball-scene-v2"
        component={BouncingBall}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="hook-problem-intro"
        component={HookProblemIntro}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="intro-api-integration"
        component={APIIntegrationScene}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-verification-security"
        component={VerificationSecurity}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="test-scene"
        component={TestScene}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-api-integration"
        component={FeatureApiIntegration}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-processing-delivery"
        component={FeatureProcessingDelivery}
        durationInFrames={145}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="benefit-verification-security"
        component={BenefitVerificationSecurity}
        durationInFrames={140}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="cta-brand-outro"
        component={InterswitchBrandOutro}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
                                        <Composition
        id="scene-problem-intro"
        component={ProblemIntro}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                      <Composition
        id="scene-api-integration"
        component={APIIntegration}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="scene-processing-delivery"
        component={ProcessingDeliveryScene}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="scene-verification-security"
        component={VerificationSecurity}
        durationInFrames={180}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="scene-outro-brand"
        component={CtaGetStarted}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="scene-problem-intro-fixed"
        component={ProblemIntro}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="scene-problem-intro-minimal"
        component={ProblemIntroMinimal}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                            <Composition
        id="problem-product-intro"
        component={ProblemProductIntro}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
                                  <Composition
        id="api-integration"
        component={APIIntegration}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
                      <Composition
        id="processing-delivery"
        component={ProcessingDeliveryScene}
        durationInFrames={180}
        fps={30}
        width={1920}
        height={1080}
      />
                            <Composition
        id="verification-security"
        component={VerificationSecurity}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
                      <Composition
        id="benefits-outro"
        component={BenefitsOutro}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                <Composition
        id="apple-reveal-scene"
        component={AppleParticleReveal}
        durationInFrames={750}
        fps={30}
        width={1280}
        height={720}
      />
                      <Composition
        id="linear-reveal"
        component={LinearLogoReveal}
        durationInFrames={90}
        fps={30}
        width={1080}
        height={1080}
      />
          <Composition
        id="linear-reveal-fixed"
        component={LinearMotion}
        durationInFrames={120}
        fps={30}
        width={1080}
        height={1080}
      />
          <Composition
        id="linear-brand-final-scene"
        component={LinearReveal}
        durationInFrames={120}
        fps={30}
        width={1080}
        height={1080}
      />
          <Composition
        id="linear-reveal-v4"
        component={LinearMotion}
        durationInFrames={120}
        fps={30}
        width={1080}
        height={1080}
      />
                                        <Composition
        id="linear-logo-reveal"
        component={LinearLogo}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="linear-reveal-v2"
        component={LinearLogoReveal}
        durationInFrames={90}
        fps={30}
        width={1080}
        height={1080}
      />
          <Composition
        id="feature-ai-automation"
        component={AIAutomationScene}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-team-collaboration"
        component={FeatureTeamCollaboration}
        durationInFrames={135}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="benefit-time-focus"
        component={BenefitTimeFocus}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="cta-sign-up"
        component={CallToAction}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="motion-art-01"
        component={MotionArtScene}
        durationInFrames={660}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="clean-test-scene"
        component={CleanTestScene}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="logo-animation"
        component={ChatGPTLogoScene}
        durationInFrames={120}
        fps={30}
        width={1080}
        height={1080}
      />
          <Composition
        id="logo-morph-spin"
        component={ChatGPTLogoScene}
        durationInFrames={120}
        fps={30}
        width={1080}
        height={1080}
      />
          <Composition
        id="logo-morph-spin-black-text"
        component={ChatGPTLogoScene}
        durationInFrames={120}
        fps={30}
        width={1080}
        height={1080}
      />
          <Composition
        id="logo-morph-spin-black-text-full-bg"
        component={ChatGPTLogoScene}
        durationInFrames={120}
        fps={30}
        width={1080}
        height={1080}
      />
          <Composition
        id="hook-unseen-force"
        component={HookUnseenForce}
        durationInFrames={90}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="intro-redefined"
        component={IntroRedefined}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="feature-integration"
        component={FeatureIntegration}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
          <Composition
        id="ai-powered-thinking-hook"
        component={AIPoweredThinkingHook}
        durationInFrames={120}
        fps={30}
        width={1920}
        height={1080}
      />
                                  <Composition
        id="scene-1776414629803"
        component={ChatGPTCTA}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
      />
    </>
  );
};
